### ISSUE TITLE
Folderpages don't show up in navigation menus 

### ISSUE THREAD

**Issue by johannes-bittner** [terminal42/contao-folderpage#32] opened 2023-04-20 10:43 UTC
Tested in a fresh Contao 4.13.20, PHP 8.0, folderpage 3.0.2 and folderpage 3.0.0: 
- pages with page type folderpage are not shown in the frontend anymore (regardless of the chosen navigation template in the navigation module)
- using folderpage 2.0.16, the extension works as expected

**Comment by fritzmg** [comment] 2023-04-20 12:43
The issue is that Contao 4.13+ does not render menu items for "unroutable types" anymore and a folderpage is an unroutable type.

**Comment by johannes-bittner** [comment] 2023-04-20 12:48
... but why does it work with Contao 4.13.20 and folderpage 2.0.16 then?

**Comment by aschempp** [comment] 2023-05-09 07:27
duplicate of https://github.com/terminal42/contao-folderpage/issues/27

**Closed by aschempp** 2023-05-09 07:27 UTC
