### ISSUE TITLE
Folderpages don't show up in navigation menus if subpage is a link

### ISSUE THREAD

**Issue by ekki82** [terminal42/contao-folderpage#34] opened 2023-05-31 07:56 UTC
When pages of the folderpages are not actual pages, but external links, neither the folderpage nor the external link is shown in navigation menus. 

Tested on Contao 4.13.23 / PHP 8.1.19

**Comment by aschempp** [comment] 2023-06-06 06:57
That does not make much sense to me. Did you enable the `Hide in navigation` option?

**Comment by ekki82** [comment] 2023-06-06 09:07
> That does not make much sense to me. Did you enable the `Hide in navigation` option?

No, "hide in navigation" is not enabled. It all works fine in Version 2.0.15, but when I updated to the newest version of folderpage, the navigation menu/category which is only an link to an external url is not shown anymore in the navigation menu frontend.

**Comment by aschempp** [comment] 2023-07-11 09:14
I cannot reproduce this, I guess you did adjust the `nav_xxx` template?

**Comment by aschempp** [comment] 2023-10-24 12:19
should be fixed by 17f50a2da2d90f43c9c14ecf872ce4c5f5920dac

**Closed by aschempp** 2023-10-24 12:19 UTC
